[package]
name = "geodnsproxy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cidr-utils = "0.5.5"
serde = "1.0.130"
serde_json = "1.0.69"
